### ISSUE TITLE
Support -rf Arguments

### ISSUE THREAD

**Issue by dan24678** [beatjunky99/rmtrash-for-Mac-OS-X#1]
I'm trying to have alias rm=rmtrash in my .bash_profile but it throws errors when it encounters scripts that pass in the -r or -f flags.

Is it possible to update your version of rmtrash to support these flags (even if "supporting" them simply means ignoring them but not throwing errors)? It'd be nice to do the same for any other flags that rm supports, but r and f seem to be the big ones.

**Comment by sebikeller** [comment]
5a813cd58d66c7009755c9f9f55712069eec661d added support for -f flag and started ignoring all options of rm except for -v and -W.

Thank you for the input.
